/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazGrafica;

/**
 *
 * @author striker
 */
public class jpComponente extends javax.swing.JPanel {

    /**
     * Creates new form jpComponente
     */
    public jpComponente(int index) {
        initComponents();
        //JPanel
        setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        this.setSize(230, 30);
        this.setVisible(true);
        //se agrega un comando al boton
        this.btn.setActionCommand("key_" + index);
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btn = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Nombre: ");
        add(jLabel1, new java.awt.GridBagConstraints());

        txtName.setText("Fernando Alvarado");
        add(txtName, new java.awt.GridBagConstraints());

        btn.setText("OK");
        add(btn, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
